name: todo_api_server

services:
  postgres:
    image: postgres:15
    container_name: todo_api_postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=todo_api
    volumes:
        - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: